#!/usr/bin/env python3
"""
suggest_related.py — candidates for data/related.json, and a check that it holds.

`related.json` maps a topic id to the ids of topics worth reading next. The page
renders it as a "See also" strip at the bottom of an open topic. It is
hand-curated on purpose: a strip generated by term overlap fills up with the
same four cards on every page in a domain, which teaches a reader to ignore it.
This script's job is to make curation cheap, not to do it.

Three modes:

  --xrefs         Print the edges already authored in the content. A
                  `<span class="xref">Exact Title</span>` is a writer saying
                  "these two belong together" and the linter already proves the
                  title resolves, so these are curation, not inference. Both
                  directions are emitted: the reader of the target benefits from
                  the link as much as the reader of the source.

  (default)       Rank suggestions by shared title terms and acronyms, weighted
                  by how rare each term is across the site. Narrow with
                  --domain <id> or --topic <slug>. Nothing is written; the
                  output is a shortlist to read and choose from.

  --check         Every id in related.json resolves to a real topic, no topic
                  points at itself, and no pair is listed twice. Exits non-zero
                  on the first kind of failure, which is the one that renders a
                  dead link.

Ids come from build.py's own stamping, so what this script calls a topic is
exactly what the page calls it.

Usage:
  python3 tools/suggest_related.py --xrefs
  python3 tools/suggest_related.py --domain sec
  python3 tools/suggest_related.py --topic cia-triad
  python3 tools/suggest_related.py --check
"""

import collections
import json
import math
import re
import sys
from html import unescape
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA = ROOT / "data"
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

from lint_content import ACRO_SPAN_RE, XREF_RE, slugify, topic_label, xref_targets  # noqa: E402
from build import _TOPIC_OPEN_RE  # noqa: E402

RELATED = DATA / "related.json"

# Words that say nothing about what a topic is about. Kept short deliberately:
# the rarity weighting below already discounts anything common, so this list
# only needs to catch words that are frequent *and* look meaningful.
STOP = set("""a an and the of for to in on with without your you it is are as at
by or vs versus what why how when where who that this these those from into out
not no does do did can cannot will would should
guide intro introduction basics basic essentials essential overview reference
deep dive quick primer part one two three
actually really just only ever never always
things thing stuff way ways rest""".split())


def topics():
    """Every topic on the site: id, domain, title, and its title's terms.

    Ids are assigned exactly as build.py assigns them — same order, same
    de-duplication carried across domains — so a suggestion can be pasted into
    related.json without a second thought about naming.
    """
    domains = json.loads((DATA / "domains.json").read_text(encoding="utf-8"))
    used, rows = set(), []
    for domain in domains:
        path = DATA / f"{domain['id']}.html"
        if not path.exists():
            continue
        body = path.read_text(encoding="utf-8")
        starts = [m.start() for m in _TOPIC_OPEN_RE.finditer(body)]
        for n, start in enumerate(starts):
            end = starts[n + 1] if n + 1 < len(starts) else len(body)
            block = body[start:end]
            label, _ = topic_label(block)
            base = slugify(label)
            slug, i = base, 2
            while slug in used:
                slug = f"{base}-{i}"
                i += 1
            used.add(slug)
            rows.append({
                "id": slug,
                "domain": domain["id"],
                "title": label,
                "terms": terms_of(label),
                "acronyms": acronyms_of(block),
                "block": block,
            })
    return rows


def terms_of(title):
    """Meaningful lowercase words in a title, singular-ish."""
    out = set()
    for w in re.findall(r"[A-Za-z][A-Za-z0-9+#]*", title):
        w = w.lower()
        if len(w) < 3 or w in STOP:
            continue
        if len(w) > 4 and w.endswith("s") and not w.endswith("ss"):
            w = w[:-1]
        out.add(w)
    return out


ACRO_RE = re.compile(r"\b[A-Z][A-Z0-9]{1,7}\b")


def acronyms_of(block):
    """Acronyms in a topic's *title*, which is where they mean something.

    Taken from the body they would match every card that happens to mention
    TCP once, which is how a "see also" strip turns into noise.
    """
    label, _ = topic_label(block)
    return {a for a in ACRO_RE.findall(label) if a not in {"THE", "AND", "FOR"}}


def xref_edges(rows):
    """Edges the writers already authored, in both directions."""
    by_title = {}
    for r in rows:
        by_title.setdefault(r["title"], r["id"])
    edges, missing = collections.defaultdict(set), []
    for r in rows:
        for _, title in xref_targets(r["block"]):
            target = by_title.get(title)
            if not target:
                missing.append((r["id"], title))
                continue
            if target == r["id"]:
                continue
            edges[r["id"]].add(target)
            edges[target].add(r["id"])
    return edges, missing


def score(a, b, weight):
    """Shared rare title terms, plus a bonus for a shared title acronym.

    Rarity matters more than count: two cards sharing "kerberos" belong
    together; two sharing "security" are two of four hundred.
    """
    shared = a["terms"] & b["terms"]
    if not shared:
        return 0.0
    s = sum(weight[t] for t in shared)
    s += 1.5 * len(a["acronyms"] & b["acronyms"])
    # A pair in different domains is the more useful suggestion: within a domain
    # the reader is already one scroll away from the other card.
    if a["domain"] != b["domain"]:
        s *= 1.25
    return s


def suggest(rows, only_domain=None, only_topic=None, per=6):
    n = len(rows)
    df = collections.Counter()
    for r in rows:
        df.update(r["terms"])
    weight = {t: math.log(n / c) for t, c in df.items()}
    by_term = collections.defaultdict(list)
    for r in rows:
        for t in r["terms"]:
            by_term[t].append(r)

    targets = rows
    if only_topic:
        targets = [r for r in rows if r["id"] == only_topic]
        if not targets:
            sys.exit(f"error: no topic with id {only_topic!r}")
    elif only_domain:
        targets = [r for r in rows if r["domain"] == only_domain]
        if not targets:
            sys.exit(f"error: no domain {only_domain!r}")

    for r in targets:
        seen, best = set(), []
        for t in r["terms"]:
            # A term shared by half the site cannot discriminate; skipping it
            # keeps the candidate set small enough to score exhaustively.
            if len(by_term[t]) > 60:
                continue
            for other in by_term[t]:
                if other["id"] == r["id"] or other["id"] in seen:
                    continue
                seen.add(other["id"])
                s = score(r, other, weight)
                if s > 0:
                    best.append((s, other))
        best.sort(key=lambda p: -p[0])
        if not best:
            continue
        print(f"\n{r['id']}  [{r['domain']}]  {r['title']}")
        for s, other in best[:per]:
            print(f"    {s:5.1f}  {other['id']}  [{other['domain']}]  {other['title']}")


def check(rows):
    if not RELATED.exists():
        print("data/related.json not found — nothing to check.")
        return 0
    related = json.loads(RELATED.read_text(encoding="utf-8"))
    ids = {r["id"] for r in rows}
    errors, warns = [], []
    pairs = set()
    for src, targets in related.items():
        if src not in ids:
            errors.append(f"{src}: no such topic")
        if not isinstance(targets, list):
            errors.append(f"{src}: value is not a list")
            continue
        if len(set(targets)) != len(targets):
            warns.append(f"{src}: lists a target twice")
        for t in targets:
            if t == src:
                errors.append(f"{src}: points at itself")
            elif t not in ids:
                errors.append(f"{src} -> {t}: no such topic")
            else:
                pairs.add((src, t))
    # One-way edges are legal but usually an oversight: the reader of the target
    # wants the link as much as the reader of the source.
    oneway = [(a, b) for a, b in pairs if (b, a) not in pairs]
    for e in errors:
        print(f"ERROR {e}")
    for w in warns:
        print(f"warn  {w}")
    total = sum(len(v) for v in related.values())
    print(f"\n{len(related)} topics carry {total} links "
          f"({len(oneway)} one-way) across {len(ids)} topics.")
    if oneway[:5]:
        print("  one-way, first few:")
        for a, b in oneway[:5]:
            print(f"    {a} -> {b}")
    return 1 if errors else 0


def main():
    args = sys.argv[1:]
    rows = topics()
    if "--check" in args:
        sys.exit(check(rows))
    if "--xrefs" in args:
        edges, missing = xref_edges(rows)
        for src in sorted(edges):
            print(json.dumps({src: sorted(edges[src])})[1:-1])
        for src, title in missing:
            print(f"# unresolved xref in {src}: {title}", file=sys.stderr)
        print(f"\n# {len(edges)} topics, "
              f"{sum(len(v) for v in edges.values())} directed edges",
              file=sys.stderr)
        return
    only_domain = only_topic = None
    if "--domain" in args:
        only_domain = args[args.index("--domain") + 1]
    if "--topic" in args:
        only_topic = args[args.index("--topic") + 1]
    suggest(rows, only_domain, only_topic)


if __name__ == "__main__":
    main()
